title_to_query = {
    "Black Friday shopping": "black friday deals",
    "Discover open job roles": "jobs at microsoft",
    "Expand your vocabulary": "define baroque",
    "Feeling symptoms?": "covid symptoms",
    "Find deals on Bing": "65 inch tv deals",
    "Find places to stay": "hotels rome italy",
    "Find somewhere new to explore": "directions to new york",
    "Gaming time": "vampire survivors video game",
    "Get your shopping done faster": "new iphone",
    "Houses near you": "apartments manhattan",
    "How's the economy?": "sp 500",
    "Learn to cook a new recipe": "how cook pierogi",
    "Learn a new recipe": "how cook pierogi",
    "Learn song lyrics": "hook blues traveler lyrics",
    "Lights, camera, action!": "lord of the rings fellowship of the bing",
    "Let's watch that movie again!": "aliens movie",
    "Plan a quick getaway": "flights nyc to paris",
    "Prepare for the weather": "weather tomorrow",
    "Quickly convert your money": "convert 374 usd to yen",
    "Search the lyrics of a song": "black sabbath supernaut lyrics",
    "Stay on top of the elections": "election news latest",
    "Too tired to cook tonight?": "Pizza Hut near me",
    "Too tired to cook?": "Pizza Hut near me",
    "Translate anything": "translate pencil sharpener to spanish",
    "What time is it?": "china time",
    "What's for Thanksgiving dinner?": "pumpkin pie recipe",
    "What's new?": "latest news",
    "Who won?": "braves score",
    "You can track your package": "usps tracking",
    "Quickly convert money": "usd to euro",
}
ignore = {
    "Bing app search",
    "Chrome extension search",
    "Get 50 entries plus 1000 points!",
    "Get 100 points with search bar",
    "Safeguard your family's info",
}
