# todo Finish translating
title_to_query = {
    "Black Friday shopping": "ofertas de black friday",
    "Discover open job roles": "trabajos en microsoft",
    "Expand your vocabulary": "definir barroco",
    "Feeling symptoms?": "síntomas de covid",
    "Find deals on Bing": "ofertas de televisores de 65 pulgadas",
    "Find places to stay": "hoteles en roma italia",
    "Find somewhere new to explore": "direcciones a nueva york",
    "Gaming time": "videojuego vampire survivors",
    "Get your shopping done faster": "nuevo iphone",
    "Houses near you": "apartamentos en manhattan",
    "How's the economy?": "sp 500",
    "Learn to cook a new recipe": "cómo cocinar pierogi",
    "Learn a new recipe": "cómo cocinar pierogi",
    "Learn song lyrics": "letras de hook blues traveler",
    "Lights, camera, action!": "el señor de los anillos la comunidad del anillo",
    "Let's watch that movie again!": "película aliens",
    "Plan a quick getaway": "vuelos de nyc a parís",
    "Prepare for the weather": "el clima de mañana",
    "Quickly convert your money": "convertir 374 usd a yen",
    "Search the lyrics of a song": "letras de black sabbath supernaut",
    "Stay on top of the elections": "últimas noticias de elecciones",
    "Too tired to cook tonight?": "Pizza Hut cerca de mí",
    "Too tired to cook?": "Pizza Hut cerca de mí",
    "Translate anything": "traducir sacapuntas al español",
    "What time is it?": "hora en china",
    "What's for Thanksgiving dinner?": "receta de pastel de calabaza",
    "Who won?": "resultado de los bravos",
    "You can track your package": "seguimiento de usps",
    "Quickly convert money": "usd a euro",
}
ignore = {
    "Bing app search",
    "Chrome extension search",
    "Get 50 entries plus 1000 points!",
    "Get 100 points with search bar",
    "Safeguard your family's info",
}
