# todo Finish translating
title_to_query = {
    "Black Friday shopping": "offres du black friday",
    "Discover open job roles": "emplois chez microsoft",
    "Expand your vocabulary": "définir baroque",
    "Feeling symptoms?": "symptômes du covid",
    "Find deals on Bing": "offres de téléviseurs 65 pouces",
    "Find places to stay": "hôtels à rome italie",
    "Find somewhere new to explore": "itinéraires vers new york",
    "Gaming time": "jeu vidéo vampire survivors",
    "Get your shopping done faster": "nouvel iphone",
    "Houses near you": "appartements à manhattan",
    "How's the economy?": "sp 500",
    "Learn to cook a new recipe": "comment cuisiner des pierogi",
    "Learn a new recipe": "comment cuisiner des pierogi",
    "Learn song lyrics": "paroles de hook blues traveler",
    "Lights, camera, action!": "le seigneur des anneaux la communauté de l'anneau",
    "Let's watch that movie again!": "film aliens",
    "Plan a quick getaway": "vols de nyc à paris",
    "Prepare for the weather": "météo de demain",
    "Quickly convert your money": "convertir 374 usd en yen",
    "Search the lyrics of a song": "paroles de black sabbath supernaut",
    "Stay on top of the elections": "dernières nouvelles des élections",
    "Too tired to cook tonight?": "Pizza Hut près de chez moi",
    "Too tired to cook?": "Pizza Hut près de chez moi",
    "Translate anything": "traduire taille-crayon en espagnol",
    "What time is it?": "heure en chine",
    "What's for Thanksgiving dinner?": "recette de tarte à la citrouille",
    "Who won?": "score des braves",
    "You can track your package": "suivi usps",
    "Quickly convert money": "usd en euro",
}
ignore = {
    "Bing app search",
    "Chrome extension search",
    "Get 50 entries plus 1000 points!",
    "Get 100 points with search bar",
    "Safeguard your family's info",
}
