title_to_query = {
    "Black Friday shopping": "offerte black friday",
    "Discover open job roles": "offerte lavoro microsoft",
    "Expand your vocabulary": "definisci barocco",
    "Feeling symptoms?": "sintomi morbillo",
    "Find deals on Bing": "offerte tv 65 pollici",
    "Find places to stay": "hotel roma italia",
    "Find somewhere new to explore": "indicazioni per Ginevra",
    "Gaming time": "gioco vampire survivors",
    "Get your shopping done faster": "nuovo samsung galaxy",
    "Houses near you": "appartamenti Firenze",
    "How's the economy?": "mib 30",
    "Learn to cook a new recipe": "ricetta giallo zafferano",
    "Learn a new recipe": "ricetta pierogi",
    "Learn song lyrics": "testo Marco mengoni due vite",
    "Lights, camera, action!": "il signore degli anelli la compagnia dell'anello",
    "Let's watch that movie again!": "film il gladiatore",
    "Plan a quick getaway": "voli da milano a catania",
    "Prepare for the weather": "meteo domani",
    "Quickly convert your money": "converti 374 euro in usd",
    "Search the lyrics of a song": "testo Laura Pausini la solitudine",
    "Stay on top of the elections": "ultime notizie elezioni",
    "Too tired to cook tonight?": "Burger King vicino a me",
    "Too tired to cook?": "McDonald vicino a me",
    "Translate anything": "traduci temperamatite in spagnolo",
    "What time is it?": "ora in cina",
    "What's for Thanksgiving dinner?": "ricetta torta di mele",
    "What's new?": "ultime notizie",
    "Who won?": "risultati inter Milan",
    "You can track your package": "tracciamento gas",
    "Quickly convert money": "euro in yen",
}
ignore = {
    "Bing app search",
    "Chrome extension search",
    "Get 50 entries plus 1000 points!",
    "Get 100 points with search bar",
    "Safeguard your family's info",
}